services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nmt
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  createbuckets:
    image: minio/mc:RELEASE.2024-06-13T20-26-00Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin &&
      /usr/bin/mc mb -p local/datasets || true &&
      /usr/bin/mc mb -p local/models || true &&
      exit 0
      "

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/nmt
      SECRET_KEY: dev-secret-change-me
      CORS_ORIGINS: http://localhost:5173,http://localhost:8080
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: ml-service
    ports:
      - "8001:8001"

volumes:
  db-data:
  minio-data:
